/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as ChatChatThreadIdRouteImport } from './routes/_chat/chat.$threadId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatChatThreadIdRoute = ChatChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/cookbook': typeof CookbookRoute
  '/upload': typeof UploadRoute
  '/': typeof ChatIndexRoute
  '/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/cookbook': typeof CookbookRoute
  '/upload': typeof UploadRoute
  '/': typeof ChatIndexRoute
  '/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/cookbook': typeof CookbookRoute
  '/upload': typeof UploadRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/chat/$threadId': typeof ChatChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cookbook' | '/upload' | '/' | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/cookbook' | '/upload' | '/' | '/chat/$threadId'
  id:
    | '__root__'
    | '/_chat'
    | '/cookbook'
    | '/upload'
    | '/_chat/'
    | '/_chat/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  CookbookRoute: typeof CookbookRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/chat/$threadId': {
      id: '/_chat/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatThreadIdRoute: typeof ChatChatThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatChatThreadIdRoute: ChatChatThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  CookbookRoute: CookbookRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
